"use client";
import { Input } from "@/components/ui/Input";
import { Select } from "@/components/ui/Select";
import { Textarea } from "@/components/ui/Textarea";
import { useCanvasStore } from "@/store/canvasStore";
import type { CanvasNodeData } from "@/types/canvas";
type Field = { key: keyof CanvasNodeData; label: string; kind?: "textarea" | "number" | "select"; options?: string[] };
const fields: Record<string, Field[]> = {
  prompt: [{ key: "title", label: "Title" }, { key: "prompt", label: "Prompt", kind: "textarea" }, { key: "negativePrompt", label: "Avoid", kind: "textarea" }, { key: "style", label: "Style" }, { key: "aspectRatio", label: "Aspect ratio", kind: "select", options: ["1:1", "16:9", "9:16", "4:5"] }],
  text: [{ key: "title", label: "Title" }, { key: "instruction", label: "Instruction", kind: "textarea" }, { key: "inputText", label: "Starting text", kind: "textarea" }],
  image: [{ key: "title", label: "Title" }, { key: "prompt", label: "Image prompt", kind: "textarea" }, { key: "model", label: "Model" }, { key: "size", label: "Size", kind: "select", options: ["1024×1024", "1536×1024", "1024×1536"] }, { key: "referenceImageUrl", label: "Reference URL" }],
  video: [{ key: "title", label: "Title" }, { key: "prompt", label: "Motion prompt", kind: "textarea" }, { key: "duration", label: "Duration (seconds)", kind: "number" }, { key: "aspectRatio", label: "Aspect ratio", kind: "select", options: ["16:9", "9:16", "1:1"] }, { key: "referenceImageUrl", label: "Reference URL" }],
  audio: [{ key: "title", label: "Title" }, { key: "prompt", label: "Audio prompt", kind: "textarea" }, { key: "voiceStyle", label: "Voice / sound style" }, { key: "duration", label: "Duration (seconds)", kind: "number" }],
  storyboard: [{ key: "title", label: "Title" }, { key: "storyBrief", label: "Story brief", kind: "textarea" }, { key: "numberOfScenes", label: "Number of scenes", kind: "number" }],
  reference: [{ key: "title", label: "Title" }, { key: "imageUrl", label: "Image URL" }, { key: "notes", label: "Notes", kind: "textarea" }],
  output: [{ key: "title", label: "Title" }, { key: "format", label: "Deliverable format", kind: "select", options: ["Creative package", "Campaign brief", "Production sheet", "JSON"] }],
};
export function PropertyPanel() { const { nodes, selectedNodeId, updateNodeData } = useCanvasStore(); const node = nodes.find((item) => item.id === selectedNodeId); if (!node) return <aside className="w-72 shrink-0 border-l border-slate-800 bg-[#0c1622] p-4"><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-500">Inspector</p><p className="mt-5 text-sm leading-6 text-slate-500">Select a node to edit its settings and review generated output.</p></aside>; const change = (key: keyof CanvasNodeData, value: string) => updateNodeData(node.id, { [key]: key === "duration" || key === "numberOfScenes" ? Number(value) : value }); return <aside className="w-72 shrink-0 overflow-y-auto border-l border-slate-800 bg-[#0c1622] p-4"><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-500">Inspector</p><div className="mt-4 space-y-4">{fields[node.data.nodeType].map((field) => <label className="block" key={field.key}><span className="mb-1.5 block text-xs text-slate-400">{field.label}</span>{field.kind === "textarea" ? <Textarea value={String(node.data[field.key] ?? "")} onChange={(event) => change(field.key, event.target.value)} /> : field.kind === "select" ? <Select value={String(node.data[field.key] ?? "")} onChange={(event) => change(field.key, event.target.value)}>{field.options?.map((option) => <option key={option}>{option}</option>)}</Select> : <Input type={field.kind === "number" ? "number" : "text"} value={String(node.data[field.key] ?? "")} onChange={(event) => change(field.key, event.target.value)} />}</label>)}</div>{node.data.output && <div className="mt-6 border-t border-slate-800 pt-4"><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-500">Last output</p><p className="mt-2 text-xs leading-5 text-slate-300">{node.data.output.summary}</p></div>}</aside>; }
